/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CambridgeRouteImport } from './routes/cambridge'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as TestIdRouteImport } from './routes/test.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CambridgeRoute = CambridgeRouteImport.update({
  id: '/cambridge',
  path: '/cambridge',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambridge': typeof CambridgeRoute
  '/essays': typeof EssaysRoute
  '/faq': typeof FaqRoute
  '/forecast': typeof ForecastRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/performance': typeof PerformanceRoute
  '/speaking': typeof SpeakingRoute
  '/support': typeof SupportRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambridge': typeof CambridgeRoute
  '/essays': typeof EssaysRoute
  '/faq': typeof FaqRoute
  '/forecast': typeof ForecastRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/performance': typeof PerformanceRoute
  '/speaking': typeof SpeakingRoute
  '/support': typeof SupportRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cambridge': typeof CambridgeRoute
  '/essays': typeof EssaysRoute
  '/faq': typeof FaqRoute
  '/forecast': typeof ForecastRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/performance': typeof PerformanceRoute
  '/speaking': typeof SpeakingRoute
  '/support': typeof SupportRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambridge'
    | '/essays'
    | '/faq'
    | '/forecast'
    | '/guide'
    | '/history'
    | '/leaderboard'
    | '/performance'
    | '/speaking'
    | '/support'
    | '/vocabulary'
    | '/writing'
    | '/test/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambridge'
    | '/essays'
    | '/faq'
    | '/forecast'
    | '/guide'
    | '/history'
    | '/leaderboard'
    | '/performance'
    | '/speaking'
    | '/support'
    | '/vocabulary'
    | '/writing'
    | '/test/$id'
  id:
    | '__root__'
    | '/'
    | '/cambridge'
    | '/essays'
    | '/faq'
    | '/forecast'
    | '/guide'
    | '/history'
    | '/leaderboard'
    | '/performance'
    | '/speaking'
    | '/support'
    | '/vocabulary'
    | '/writing'
    | '/test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CambridgeRoute: typeof CambridgeRoute
  EssaysRoute: typeof EssaysRoute
  FaqRoute: typeof FaqRoute
  ForecastRoute: typeof ForecastRoute
  GuideRoute: typeof GuideRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PerformanceRoute: typeof PerformanceRoute
  SpeakingRoute: typeof SpeakingRoute
  SupportRoute: typeof SupportRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingRoute: typeof WritingRoute
  TestIdRoute: typeof TestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambridge': {
      id: '/cambridge'
      path: '/cambridge'
      fullPath: '/cambridge'
      preLoaderRoute: typeof CambridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CambridgeRoute: CambridgeRoute,
  EssaysRoute: EssaysRoute,
  FaqRoute: FaqRoute,
  ForecastRoute: ForecastRoute,
  GuideRoute: GuideRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PerformanceRoute: PerformanceRoute,
  SpeakingRoute: SpeakingRoute,
  SupportRoute: SupportRoute,
  VocabularyRoute: VocabularyRoute,
  WritingRoute: WritingRoute,
  TestIdRoute: TestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
